# Generated by Django 4.0 on 2022-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
